language: python
python:
- 3.8.5
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
- python manage.py makemigrations
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: Bbj8bAXCyI/3gDdIWbEpzgE69okYYzXpKobJMyxK3LOUkGAQAnxTRKV36jqGGp/XfWKSQHyR6Rz9J3iNR2+Xpe35wV7dttrYJGoDt9yT5d4qE8HE+5eYyp5t9QJQnYxgDuvsbGiVryXzL80FEi/YRC3ViME9uxgblnqXVK/pgdvuU6/bw0TmGSKbLRurcvXqChlsFIefuV6zhGa6CZQyVUiWcmLt+PAGNGJplDCrpEXRpOxZNDHd75nwNer27/dTbOjE/ypDcgxY6WK3dmj0YYsaNTzB09XLnL9V6KonigosMl4sHeCRHHpcka3t4/cq/Za4LLhi/xIL3jItx86MIPvtB++vOI77PLpNv+1Uv6CEC+NlNmx30TZ8kon97DohM92gnXfoxP6YhNd06+yhoBqXSCRcTSS4gf31Ai0Y5yHciU7WYOUDNLCryxhakE0NNX5ro580Ei7ndW9mp6t9/Nkxrjl7R9/qdvEiXi8OOUEX9H+lpm6daTn9DQt6mPWEwdzJG9YvBXSHxGwVdPewNhJjjhTx3BAG34eVd7m8s8ArbOPLbD5txJJxCDzGoQxhwr/oXlIpNeGh+j0GhWcW+NG9M2G/0UeLZLa8blm/TpOTIRd8nvmCSgE3VDmsqOKuLB3v3aypYbZS2teFKXQAd+yN56X5twor4oHQI3iZSYA=
  app: project-2-11
  on:
    repo: uva-cs3240-f20/project-2-11
