# Generated by Django 3.1.1 on 2020-10-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20201025_1154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
