# Generated by Django 3.1.2 on 2020-10-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('info', models.TextField()),
                ('starts', models.DateTimeField(verbose_name='Starts')),
                ('ends', models.DateTimeField(verbose_name='Ends')),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
