# Generated by Django 3.1.2 on 2020-10-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts',
        ),
    ]
