# Generated by Django 3.1.1 on 2020-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='xcoord',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='ycoord',
            field=models.FloatField(default=0.0),
        ),
    ]
