# Generated by Django 3.1.1 on 2020-10-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201011_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FilePathField(),
        ),
    ]
